import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>Poços de Caldas</h1>
        <p className={styles.description}>
          Sobre a cidade, pessoas que habitam e memórias de uma sociedade.
        </p>
        <img
          alt="Telephone Booths, 1967"
          src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
          width={"100%"}
        />
        <p>
          Richard Estes
          <br />
          Telephone Booths, 1967
          <br />
          Acrylic on masonite. 122 x 175.3 cm
          <br />
          Museo Nacional Thyssen-Bornemisza, Madrid
        </p>

        <div className={styles.gallery}>
          <img
            alt="Telephone Booths, 1967"
            src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
            width={"100%"}
          />
          <img
            alt="Telephone Booths, 1967"
            src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
            width={"100%"}
          />
          <img
            alt="Telephone Booths, 1967"
            src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
            width={"100%"}
          />
          <img
            alt="Telephone Booths, 1967"
            src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
            width={"100%"}
          />
          <img
            alt="Telephone Booths, 1967"
            src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
            width={"100%"}
          />

        </div>

        <blockquote className={styles.subtitle}>
          "A cidade é uma combinação de muitas coisas: memória, desejos, signos de uma linguagem; é um lugar de troca, como qualquer
          livro de história econômica lhe dirá - só que essas trocas não são apenas trocas de mercadorias, mas também envolvem palavras,
          desejos e memórias. <br />Italo Calvino
        </blockquote>
      </main>
    </>
  )
}
