import { Fragment, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

import scrollX from '@/utils/scrollX'

import ruaPernambuco from "@/assets/images/rua_pernambuco.jpg"

export default function Home() {

  useEffect(() => {
    scrollX("gallery")
  }, [])
  return (
    <Fragment>
      <Head>
        <title>Poços de Caldas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>Poços de Caldas</h1>
        <p className={styles.description}>
          Sobre a cidade, pessoas que habitam e memórias de uma sociedade.
        </p>
        <div className={styles.placeholder}>
          <Image
            src={ruaPernambuco}
            height={800}
            style={{
              width: "100%",
              objectFit: "cover"
            }}
          />

        </div>
        <p className={styles["introduction"]}>
          There are certain types of cities and ways of living based on caring. Indeed, caring for urban denizens and their environment, democratic participation, diversity, cultural legacy and creative ecosystems re-naturalises life in the city.
          This project opens the doors of the Museo Nacional Thyssen-Bornemisza in order to collectively conceive and imagine other ways of occupying and sharing our cities.
          We welcome here some voices from literature, art, architecture and urban development to share their views on this matter and reflect on its evolution through time.
          We therefore invite you to explore this website, wandering freely (drift mode) or following our proposed itinerary (path option): access the content in video, podcast, text or image format, discover this pictorial-literary city by day or by night, and share your own experiences about the city you call home.
        </p>
        <div className={styles["gallery-container"]} id="gallery">
          <div className={styles.gallery}>
            <img
              alt="Telephone Booths, 1967"
              src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
              width={"100%"}
              height={"100%"}
            />
            <div></div>
            <img
              alt="Telephone Booths, 1967"
              src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
              width={"100%"}
              height={"100%"}
            />
            <div></div>
            <div></div>
            <img
              alt="Telephone Booths, 1967"
              src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
              width={"100%"}
              height={"100%"}
            />
            <div></div>

            <img
              alt="Telephone Booths, 1967"
              src="https://www.museothyssen.org/webdocs/conectathyssen/cartas-amor-ciudades/wp-content/uploads/2022/07/1977-5.jpg"
              width={"100%"}
              height={"100%"}
            />
            <div></div>
          </div>
        </div>


        <blockquote className={styles["home-footer"]}>
          "A cidade é uma combinação de muitas coisas: memória, desejos, signos de uma linguagem; é um lugar de troca, como qualquer
          livro de história econômica lhe dirá - só que essas trocas não são apenas trocas de mercadorias, mas também envolvem palavras,
          desejos e memórias."<br />Italo Calvino
        </blockquote>

        {/*
        
                <p>
          Richard Estes
          <br />
          Telephone Booths, 1967
          <br />
          Acrylic on masonite. 122 x 175.3 cm
          <br />
          Museo Nacional Thyssen-Bornemisza, Madrid
        </p>
         */}
      </main>
    </Fragment>
  )
}
